apiVersion: apps/v1
kind: Deployment
metadata:
  name: isp-optimizer-deployment
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: isp-optimizer
  template:
    metadata:
      labels:
        app: isp-optimizer
    spec:
      containers:
      - name: isp-container
        image: isp-optimizer-image
        imagePullPolicy: Never 