apiVersion: v1
kind: Service
metadata:
  name: isp-loadbalancer
spec:
  selector:
    app: isp-optimizer # نفس الاسم الموجود في الـ Deployment
  ports:
    - protocol: TCP
      port: 80         # المنفذ الخارجي
      targetPort: 5000 # منفذ التطبيق
  type: LoadBalancer