apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: isp-data-analysis-
spec:
  entrypoint: main
  templates:
  - name: main
    container:
      image: isp-optimizer-image:v2
      imagePullPolicy: Never # ليستخدم الصورة التي بنيناها محلياً
      command: [python]
      args: ["app.py"]