name: Cloud Cost Sentinel Pipeline

on:
  # Schedule: Run every day at 00:00 UTC to clean resources
  schedule:
    - cron: '0 0 * * *'
  # Allow manual trigger for the Demo
  workflow_dispatch:

jobs:
  finops-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install boto3

      - name: Run Sentinel Cost Optimization
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "eu-west-3" # Paris Region
        run: python sentinel-finops-layer/sentinel_logic.py

      - name: Notify Team on Success
        if: success()
        run: echo "FinOps Daily Scan Completed. Resources optimized."